# Generated by Django 5.0.6 on 2024-05-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='skins',
            field=models.ManyToManyField(to='shop.cartskin', verbose_name='Скины'),
        ),
        migrations.AddField(
            model_name='order',
            name='skins',
            field=models.ManyToManyField(to='shop.cartskin', verbose_name='Скины'),
        ),
    ]
