# Generated by Django 5.0.6 on 2024-05-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_skin_only_one_cartskin'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='index',
            field=models.IntegerField(default=0, verbose_name='Индекс'),
        ),
    ]
