# Generated by Django 5.0.6 on 2024-05-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_skins_order_skins'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='shop.cartitem', verbose_name='Предметы'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='skins',
            field=models.ManyToManyField(blank=True, to='shop.cartskin', verbose_name='Скины'),
        ),
    ]
