# Generated by Django 5.0.6 on 2024-05-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_color_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='index',
        ),
        migrations.AddField(
            model_name='rarity',
            name='index',
            field=models.IntegerField(default=0, verbose_name='Индекс'),
        ),
    ]
