# Generated by Django 5.0.6 on 2024-05-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_is_active_alter_cart_items_alter_cart_skins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
