# Generated by Django 5.0.6 on 2024-05-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_item_unity_id_remove_skin_unity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unity_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID в Unity'),
        ),
        migrations.AddField(
            model_name='skin',
            name='unity_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID в Unity'),
        ),
    ]
