# Generated by Django 5.0.6 on 2024-05-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='skins',
            field=models.ManyToManyField(to='account.userskin', verbose_name='Скины'),
        ),
    ]
