# Generated by Django 5.0.6 on 2024-05-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userinfo_skins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='items',
            field=models.ManyToManyField(blank=True, to='account.useritem', verbose_name='Предметы'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='skins',
            field=models.ManyToManyField(blank=True, to='account.userskin', verbose_name='Скины'),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='userskin',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
